// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"database/sql"
)

type Feature struct {
	ID          uint32
	Createdat   sql.NullTime
	Updatedat   sql.NullTime
	Deletedat   sql.NullTime
	Title       string
	Description string
	Productid   uint32
}

type Product struct {
	ID          uint32
	Createdat   sql.NullTime
	Updatedat   sql.NullTime
	Deletedat   sql.NullTime
	Name        string
	Description string
	Link        string
	BookPict    string
}

type User struct {
	ID        uint32
	Createdat sql.NullTime
	Updatedat sql.NullTime
	Deletedat sql.NullTime
	Username  string
	Email     string
	Number    string
	Address   string
	Password  string
	Token     string
}
